ATSERVICES:
  - CASSANDRA:
      image: stratio/cassandra-lucene-index:%%VERSION
      sleep: 30
      volumes:
        - jts:1.14.0
      env:
        - LOCAL_JMX=no

ATPARAMETERS: >
    -Dit.host=%%CASSANDRA
    -DJACOCO_SERVER=%%CASSANDRA
    -Dit-embedded=false

